# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8450d2fe9fc657b073102d5d76fa9c4f"
name = "GeoTargetPro"
application_url = "https://geo-target-pro.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
	"https://geo-target-pro.vercel.app/auth/callback",
	"https://geo-target-pro.vercel.app/auth/shopify/callback",
	"https://geo-target-pro.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://geo-target-pro.vercel.app/public/geotarget"
subpath = "geotarget-pro"
prefix = "apps"
