# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cd612c6f405fc1c4c1b1286e2d0da584"
name = "GeoTargetPro"
application_url = "https://probe-requiring-desired-knock.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
	"https://probe-requiring-desired-knock.trycloudflare.com/auth/callback",
	"https://probe-requiring-desired-knock.trycloudflare.com/auth/shopify/callback",
	"https://probe-requiring-desired-knock.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://probe-requiring-desired-knock.trycloudflare.com/public/geotarget"
subpath = "geotarget-pro"
prefix = "apps"
